name: E2E (Playwright)

on:
  workflow_dispatch:

jobs:
  checkout:

    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
      - name: Checkout adyen-testing-suite
        uses: actions/checkout@v2
        with:
          repository: adyen-examples/adyen-testing-suite
          path: './adyen-testing-suite'

  e2e-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v1
      - uses: microsoft/playwright-github-action@v1
      - name: Install dependencies and run tests
        run: npm install && npx playwright test adyen-testing-suite
